MAKE="make KDIR=${kernel_source_dir}"
CLEAN="make KDIR=${kernel_source_dir} clean"
PACKAGE_NAME=nuc_wmi
PACKAGE_VERSION=2.0
AUTOINSTALL=yes
POST_INSTALL="packaging/install_touchpad_service.sh"

BUILT_MODULE_NAME[0]=nuc_wmi
DEST_MODULE_LOCATION[0]=/kernel/drivers/platform/x86

BUILT_MODULE_NAME[1]=ite8291r3
DEST_MODULE_LOCATION[1]=/kernel/drivers/hid
